# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.

version: 2
updates:
# Enable version updates for GitHub actions
- package-ecosystem: "github-actions" # See documentation for possible values
  directory: "/"
  schedule:
    interval: "weekly"
    day: "sunday"
    time: "16:00"
  groups:
    all-actions:
      patterns: [ "*" ]
# Enable version updates for Docker
- package-ecosystem: "docker"
  directory: "/"
  schedule:
    interval: "weekly"
    day: "sunday"
    time: "16:00"
